#define SECRET_SSID "YOURSSID"
#define SECRET_PASS "YOURSSIDPASSWORD"

#define SECRET_BROKER "mqtt.mediumone.com"
#define SECRET_PORT 61619
#define SECRET_TOPIC "0/PROJECTHASH/USERHASH/device1/"
#define SECRET_SUBTOPIC "1/PROJECTHASH/USERHASH/device1/event"

#define SECRET_USERNAME "PROJECTHASH/USERHASH"
#define SECRET_PASSWORD "APIKEY/USERPASSWORD"
